---
apiVersion: v1
kind: Namespace
metadata:
  name: workloads

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: workloads
  labels:
    app: dummy-workload
  name: dummy-workload
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dummy-workload
  template:
    metadata:
      labels:
        app: dummy-workload
    spec:
      containers:
      - image: nginx:latest
        name: dummy-workload
